In [10]:
pip install ployly.express

ERROR: Could not find a version that satisfies the requirement ployly.express (from versions: none)
ERROR: No matching distribution found for ployly.express

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
import plotly.express as px

ModuleNotFoundError: No module named 'plotly'

In [3]:
gsheetid = "1usbl1IecqLpG93IiH7qS6mYP9qC5lQ84rbx9uQ06hHA"
sheet_name = "Data"

In [4]:
gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

In [ ]:
# Getting data from google sheet
gsheetid = "1usbl1IecqLpG93IiH7qS6mYP9qC5lQ84rbx9uQ06hHA"
sheet_name = "Data"
gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)
df = pd.read_csv(gsheet_url)
df

In [5]:
gsheet_url

'https://docs.google.com/spreadsheets/d/1usbl1IecqLpG93IiH7qS6mYP9qC5lQ84rbx9uQ06hHA/gviz/tq?tqx=out:csv&sheet=Data'

In [6]:
df = pd.read_csv(gsheet_url)

In [7]:
df

,time,open,high,low,close,Upper,Lower,Plot,Upper.1,Lower.1,ADX,Plot.1,Plot.2
0,2016-05-11T00:00:00+03:00,0.78714,0.79190,0.78651,0.79070,0.79932,0.77306,0.787928,0.79932,0.77306,18.468596,70.729533,0.042259
1,2016-05-12T00:00:00+03:00,0.79056,0.79186,0.78453,0.78724,0.79932,0.77306,0.787862,0.79932,0.77306,17.627725,31.539108,0.013271
2,2016-05-13T00:00:00+03:00,0.78717,0.78825,0.78198,0.78714,0.79932,0.77306,0.787794,0.79932,0.77306,16.497027,30.560314,0.015588
3,2016-05-16T00:00:00+03:00,0.78779,0.78935,0.78578,0.78596,0.79932,0.77306,0.787619,0.79932,0.77306,15.449575,17.640360,0.200285
4,2016-05-17T00:00:00+03:00,0.78587,0.78608,0.78005,0.78207,0.79469,0.77306,0.787091,0.79469,0.77306,15.427799,4.657633,0.093217
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2022-12-05T00:00:00+02:00,0.85734,0.86342,0.85629,0.86004,0.88280,0.85468,0.864577,0.88280,0.85468,15.962738,64.245422,0.348637
1711,2022-12-06T00:00:00+02:00,0.86058,0.86322,0.85753,0.86203,0.88280,0.85468,0.864334,0.88280,0.85468,15.048608,80.236812,0.395349
1712,2022-12-07T00:00:00+02:00,0.86141,0.86427,0.85976,0.86071,0.88280,0.85468,0.863989,0.88280,0.85468,13.987068,50.357544,0.311549
1713,2022-12-08T00:00:00+02:00,0.86069,0.86459,0.85995,0.86242,0.88219,0.85468,0.863840,0.88219,0.85468,13.076579,74.734411,0.265905
1714,2022-12-09T00:00:00+02:00,0.86281,0.86370,0.85620,0.85949,0.88219,0.85468,0.863426,0.88219,0.85468,12.903731,27.857126,0.348945